# Development Profile
spring.datasource.url=jdbc:mysql://localhost:3306/itpm_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
